.TH GSL 3 "GNU Scientific Library" "GSL Team" \" -*- nroff -*-
.SH NAME
gsl - GNU Scientific Library
.SH SYNOPSIS
#include <gsl/...>
.SH DESCRIPTION
The GNU Scientific Library (GSL) is a collection of routines for
numerical computing.  The routines are written from scratch by the GSL
team in C, and are meant to present a modern Applications Programming
Interface (API) for C programmers, while allowing wrappers to be
written for very high level languages.
.PP
GSL is currently in beta-test release, for people who want to test
the library itself. When the library is complete and fully tested it
will be announced for general use.
.PP
For more information please consult the GSL Reference Manual,
which is available as an info file.
